# -*- coding: utf-8 -*-
"""datascience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZykJVIsoXUuvn8fX16TUHe4aHYXIMwsX
"""

import pandas as pd
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt

import os
import pandas as pd

file_path = '/content/Dataset_Transaksi_Inferensial.csv'

if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    print("=== 5 Baris Pertama Data ===")
    print(df.head())
    print("\n" + "="*50 + "\n")
else:
    print(f"[ERROR] Berkas tidak ditemukan di: {file_path}")
    print("Silakan unggah berkas 'Dataset_Transaksi_Inferensial.csv' ke Google Colab terlebih dahulu.")

grup_biru = df[df['Warna_Tombol'] == 'Biru']['Nominal_Transaksi']
grup_hijau = df[df['Warna_Tombol'] == 'Hijau']['Nominal_Transaksi']

t_stat, p_value = stats.ttest_ind(grup_biru, grup_hijau)
print(f"T-Statistic: {t_stat:.4f}")
print(f"P-Value: {p_value:.4f}")

if p_value < 0.05:
    print("Kesimpulan: Tolak H0. Terdapat perbedaan signifikan antara tombol Biru dan Hijau.")
else:
    print("Kesimpulan: Gagal Tolak H0. Tidak ada perbedaan signifikan.")

print("\n" + "="*50 + "\n")

ewallet = df[df['Metode_Bayar'] == 'E-Wallet']['Nominal_Transaksi']
transfer = df[df['Metode_Bayar'] == 'Transfer Bank']['Nominal_Transaksi']
kredit = df[df['Metode_Bayar'] == 'Kartu Kredit']['Nominal_Transaksi']

f_stat, p_val_anova = stats.f_oneway(ewallet, transfer, kredit)
print(f"F-Statistic: {f_stat:.4f}")
print(f"P-Value ANOVA: {p_val_anova:.4f}")

if p_val_anova < 0.05:
    print("Kesimpulan: Tolak H0. Ada perbedaan rata-rata transaksi yang signifikan antar metode pembayaran.")
else:
    print("Kesimpulan: Gagal Tolak H0. Tidak ada perbedaan yang signifikan.")

print("\n" + "="*50 + "\n")

korelasi, p_val_corr = stats.pearsonr(
    df['Waktu_Akses_Menit'],
    df['Nominal_Transaksi']
)

print(f"Koefisien Korelasi (r): {korelasi:.4f}")
print(f"P-Value: {p_val_corr:.4f}")

plt.figure(figsize=(8, 5))
sns.scatterplot(
    x='Waktu_Akses_Menit',
    y='Nominal_Transaksi',
    data=df
)
plt.title('Hubungan Waktu Akses dan Nominal Transaksi', fontsize=14, pad=15)
plt.xlabel('Waktu Akses (Menit)', fontsize=12)
plt.ylabel('Nominal Transaksi (Rp)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()